version: '2.1'

branch-defaults:
  dev:
    environment: dev-my-application
environment-defaults:
  dev-my-application:
    branch: null
    repository: null
global:
  default_region: us-east-1
  application_name: dev-my-application
  default_platform: 
    arn:aws:elasticbeanstalk:us-east-1::platform/Docker running on
    64bit Amazon Linux 2/3.4.17
  sc: git
  workspace_type: Application
