version: 2.1

base_config: &base_config
  docker:
      - image: cimg/ruby:3.1.2
      working_directory: ~/app

orbs:
  aws-cli: circleci/aws-cli@1.3.2

jobs:
  deploy:
    docker:
      - image: cimg/python:3.7
    working_directory: /
    steps:
      - attach_workspace:
          at: /
      - checkout
      - run:
          name: Installing deployment dependencies
          working_directory: /
          command: |
            sudo apt-get -y -qq update
            sudo apt-get install python3-pip python3-dev build-essential
            sudo pip3 install awsebcli
      - run:
          name: Deploying
          command: eb deploy $CIRCLE_BRANCH-my-application

workflows:
  version: 2
  build:
    jobs:
      - deploy:
          filters:
            branches:
              only:
                - dev
